name: Test package installation
on: 
    push:
        branches:
            ["master", "main", "feature/*"]
    pull_request:
        branches:
            ["master", "main", "feature/*"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'
            - name: Install package
              run: |
                  python -m pip install --upgrade pip
                  pip install .
            - name: Check for version
              run: |
                  rstk --version
              
